---
- hosts: managed_node

  vars:
    tmp_dir: /tmp

  tasks:

  - name: Sync requirements.txt
    synchronize:
      src: requirements.txt
      dest: "{{ tmp_dir }}"

  - name: Create python virtual env and install requirements
    pip:
      requirements: "{{ tmp_dir }}/requirements.txt"
      virtualenv_command: python3 -m venv
      virtualenv: "{{ tmp_dir }}/venv"

  - name: Sync pyvenv bash script
    synchronize:
      src: pyvenv
      dest: "{{ tmp_dir }}/venv/bin"

  - name: Sync terraform dir
    synchronize:
      src: ../../
      dest: "{{ tmp_dir }}/terraform"