---
- hosts: 127.0.0.1
  connection: local

  tasks:

  ## Create Bastion as EC2 instance w/ AMI, SecGroup, & S3 read permissions from IAM
  ## Wait for RDS to become available
  - name: Create bastion host
    amazon.aws.ec2_instance:
      name: "{{ project_id }}-bastion-host"
      key_name: "prod-ssh-key"
      vpc_subnet_id: "{{ public_subnet_ids | shuffle }} "
      instance_type: t2.micro
      security_group:
      network:
        assign_public_ip: true
      image_id:
      tags:
        Name: "{{ project_id }}-bastion-host"

