version: '3'

networks:
  db-net:

volumes:
  db-volume:

services:
  db:
    image: mysql:8
    container_name: mysql
    env_file: .env
    volumes:
      - db-volume:/var/lib/mysql
      - ./mysql_startup_scripts:/docker-entrypoint-initdb.d
    networks:
      - db-net
    ports:
      - 3306:3306

  flights-spring-api:
    image: austinbaugh/utopia-flights-spring-api:latest
    build: ../spring-apis/flights-api
    container_name: flights-spring-api
    depends_on:
       - db
    environment:
      MYSQL_HOST: mysql:3306
    networks:
      - db-net
    expose:
      - 8080
    ports:
      - 8080:8080

  users-spring-api:
    image: austinbaugh/utopia-users-api:latest
    build: ../spring-apis/users-api
    container_name: users-spring-api
    depends_on:
       - db
    environment:
      MYSQL_HOST: mysql:3306
    networks:
      - db-net
    expose:
      - 8090
    ports:
      - 8090:8080

  bookings-spring-api:
    image: austinbaugh/utopia-bookings-spring-api:latest
    build: ../spring-apis/bookings-api
    container_name: bookings-spring-api
    depends_on:
       - db
    environment:
      MYSQL_HOST: mysql:3306
    networks:
      - db-net
    expose:
      - 8100
    ports:
      - 8100:8080
