version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/startup_scripts:/docker-entrypoint-initdb.d
    networks:
      - db_net
    ports:
      - 3306:3306
  flights-api:
    image: austinbaugh/utopia-flights-api:latest
    depends_on:
       - db
    container_name: flights-api
    restart: always
    environment:
      MYSQL_HOST: mysql:3306
    networks:
      - db_net
    expose:
      - 8080
    ports:
      - 8080:8080
  users-api:
    image: austinbaugh/utopia-users-api:latest
    depends_on:
       - db
    container_name: users-api
    restart: always
    environment:
      MYSQL_HOST: mysql:3306
    networks:
      - db_net
    expose:
      - 8090
    ports:
      - 8090:8080
  bookings-api:
    image: austinbaugh/utopia-bookings-api:latest
    depends_on:
       - db
    container_name: bookings-api
    restart: always
    environment:
      MYSQL_HOST: mysql:3306
    networks:
      - db_net
    expose:
      - 8100
    ports:
      - 8100:8080
networks:
  db_net:
