jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Read:authenticated"
        - "Overall/Administer:admin"
  remotingSecurity:
    enabled: true
  globalNodeProperties:
    - envVars:
        env:
          - key: PATH
            value: '$HOME/tools/terraform-0.11:$PATH'
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
unclassified:
  location:
    url: http://127.0.0.1:8080/
credentials:
  system:
    domainCredentials:
      - credentials:
        - aws:
            scope: GLOBAL
            id: "jenkins"
            accessKey: "${AWS_ACCESS_KEY}"
            secretKey: "${AWS_SECRET_ACCESS_KEY}"
            description: "AWS Credentials"
tool:
  terraform:
    installations:
      - name: "terraform"
        home: "terraform-0.11"
        properties:
          - installSource:
              installers:
                - terraformInstaller:
                    id: "0.11.9-linux-amd64"
jobs:
  - script: >
      folder('Austin') {
        description("Austin's Pipelines")
      }
  - script: >
      pipelineJob('Austin/Terraform') {
        description()
        keepDependencies(false)
        disabled(false)
        properties {
          disableConcurrentBuilds()
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/Heads-in-The-Cloud/devops-AB.git')
                }
                branch('*/feature-eks')
              }
              scriptPath('terraform/Jenkinsfile')
            }

            lightweight()
          }
        }
      }


