---
- hosts: managed_node

  vars:
    tmp_dir: /tmp

  tasks:

  - name: Create jcasc dir
    file:
      dest: "{{ tmp_dir }}/jcasc"
      state: directory
  - name: Copy Dockerfile for Jenkins
    copy:
      src: Dockerfile
      dest: "{{ tmp_dir }}/jcasc"
  - name: Copy plugins.txt for Jenkins
    copy:
      src: plugins.txt
      dest: "{{ tmp_dir }}/jcasc"
  - name: Copy casc.yaml for Jenkins
    copy:
      src: casc.yaml
      dest: "{{ tmp_dir }}/jcasc"
