---
- hosts: managed_node

  vars:
    project_id: AB-utopia
    containers:
      - reverse-proxy
      - bookings-microservice
      - flights-microservice
      - users-microservices
    jwt_secret: "{{ lookup('password', 'credentials/jwt_secret.txt chars=ascii_lowercase,digits length=32') }}"
    users:
      jenkins_admin:
        name: admin
        password: "{{ lookup('password', 'credentials/jenkins_admin.txt chars=ascii_lowercase,digits length=16') }}"
      db_admin:
        name: root
        password: "{{ lookup('password', 'credentials/db_admin.txt chars=ascii_lowercase,digits length=16') }}"
      db_user:
        name: user
        password: "{{ lookup('password', 'credentials/db_user.txt chars=ascii_lowercase,digits length=16') }}"

  tasks:

  - name: Create python venv
    shell: python -m venv /tmp

  - name: Install docker compose and localstack
    shell: pip install docker-compose moto localstack

  - name: Copy docker-compose.yml
    copy:
      src: docker-compose.yml
      dest: /tmp

  - name: Install awscli-local
    shell: pip install awscli-local[ver1]

  - name: Create jcasc dir
    file:
      path: /tmp/jcasc
      state: directory
  - name: Copy Dockerfile for Jenkins
    copy:
      src: Dockerfile
      dest: /tmp/jcasc
  - name: Copy plugins.txt for Jenkins
    copy:
      src: plugins.txt
      dest: /tmp/jcasc
  - name: Copy casc.yaml for Jenkins
    copy:
      src: casc.yaml
      dest: /tmp/jcasc


