# ---------------------------------------------------------------------------- #
#             Deploy pre-configured Jenkins instance for deveopment            #
# ---------------------------------------------------------------------------- #
---
- hosts: managed_node

  vars:

    users:
      jenkins_admin:
        name: admin
        password: "{{ lookup('password', 'credentials/jenkins_admin.txt chars=ascii_lowercase,digits length=16') }}"
    tmp_dir: /tmp

  tasks:

  - name: Create jcasc dir
    file:
      dest: "{{ tmp_dir }}/jcasc"
      state: directory
  - name: Sync Dockerfile for Jenkins
    synchronize:
      src: Dockerfile
      dest: "{{ tmp_dir }}/jcasc"
  - name: Sync plugins.txt for Jenkins
    synchronize:
      src: plugins.txt
      dest: "{{ tmp_dir }}/jcasc"
  - name: Sync casc.yaml for Jenkins
    synchronize:
      src: casc.yaml
      dest: "{{ tmp_dir }}/jcasc"

  - name: Build jenkins image
    containers.podman.podman_image:
      name: jenkins-ab
      path: "{{ tmp_dir }}/jcasc"
      force: yes
      build:
        format: docker

  - name: Start jenkins container
    containers.podman.podman_container:
      name: jenkins
      image: jenkins-ab
      recreate: yes
      ports:
        - "8080:8080"
      env:
        AWS_ACCESS_KEY: local
        AWS_SECRET_ACCESS_KEY: local
        JENKINS_ADMIN_ID: "{{ users.jenkins_admin.name }}"
        JENKINS_ADMIN_PASSWORD: "{{ users.jenkins_admin.password }}"

  - debug:
      msg: "id: {{ users.jenkins_admin.name }}, password: {{ users.jenkins_admin.password }}"
