---
- hosts: 127.0.0.1
  connection: local

  vars:

    users:
      jenkins_admin:
        name: admin
        password: "{{ lookup('password', 'credentials/jenkins_admin.txt chars=ascii_lowercase,digits length=16') }}"
    tmp_dir: /tmp

  tasks:

  - name: Start jenkins container
    containers.podman.podman_container:
      name: jenkins
      build: "{{ tmp_dir }}/jcasc"
      ports:
        - "80:8080"
      env:
        JENKINS_ADMIN_ID: "{{ users.jenkins_admin.name }}"
        JENKINS_ADMIN_PASSWORD: "{{ users.jenkins_admin.password }}"

  - debug:
      msg: "id: {{ users.jenkins_admin.name }}, password: {{ users.jenkins_admin.password }}"
