---
- hosts: managed_node

  vars:
    users:
      jenkins_admin:
        name: admin
        password: "{{ lookup('password', 'credentials/jenkins_admin.txt chars=ascii_lowercase,digits length=16') }}"
      db_admin:
        name: root
        password: "{{ lookup('password', 'credentials/db_admin.txt chars=ascii_lowercase,digits length=16') }}"
      db_user:
        name: user
        password: "{{ lookup('password', 'credentials/db_user.txt chars=ascii_lowercase,digits length=16') }}"

  tasks:

  - name: Create python venv
    shell: python -m venv /tmp

  - name: Install docker compose and localstack
    shell: pip install docker-compose moto localstack

  - name: Copy docker-compose.yml
    copy:
      src: docker-compose.yml
      dest: /tmp

  - name: Install awscli-local
    shell: pip install awscli-local[ver1]

  - name: Create jcasc dir
    file:
      path: /tmp/jcasc
      state: directory
  - name: Copy Dockerfile for Jenkins
    copy:
      src: Dockerfile
      dest: /tmp/jcasc
  - name: Copy plugins.txt for Jenkins
    copy:
      src: plugins.txt
      dest: /tmp/jcasc
  - name: Copy casc.yaml for Jenkins
    copy:
      src: casc.yaml
      dest: /tmp/jcasc

  - name: docker-compose up
    shell: docker-compose -f /tmp/docker-compose.yml up -d --force-recreate
    environment:
      TMPDIR: /tmp
      AWS_REGION: us-west-2
      ANSIBLE_NODE_HOST: "{{ inventory_hostname }}"
      LOCALSTACK_API_KEY: "{{ localstack_api_key }}"
      JENKINS_ADMIN_ID: "{{ users.jenkins_admin.name }}"
      JENKINS_ADMIN_PASSWORD: "{{ users.jenkins_admin.password }}"

  - name: Create HTTP proxy for Localstack dashboard
    local_action: command
      podman run -d
        --name=nginx
        -v /home/sheep/work/utopia/devops/JCasC/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
        -p 4566:4566
        --env DOMAIN=localhost
        --env ANSIBLE_NODE_HOST="{{ inventory_hostname }}"
        --add-host "{{ inventory_hostname }}":"{{ ansible_default_ipv4.address }}"
        docker.io/nginx

      #  - name: Start localstack
      #    shell: python3 -m localstack.cli.main start -d
      #    environment:
      #      DEFAULT_REGION: us-west-2
      #      EDGE_BIND_HOST: 192.168.0.4
      #      LOCALSTACK_API_KEY: "{{ localstack_api_key }}"

        #  - name: Wait for container to start
        #    shell: python3 -m localstack.cli.main wait

       #  - name: Create S3 bucket for Terraform state file
       #    shell: awslocal s3api create-bucket --bucket ab-utopia
       #    environment:
       #      AWS_REGION: us-west-2
       #      AWS_ACCESS_KEY_ID: local
       #      AWS_SECRET_ACCESS_KEY: local

  - debug:
      msg: "id: {{ users.jenkins_admin.name }}, password: {{ users.jenkins_admin.password }}"
