# ---------------------------------------------------------------------------- #
#             Deploy pre-configured Jenkins instance for deveopment            #
# ---------------------------------------------------------------------------- #
---
- hosts: 127.0.0.1
  connection: local

  vars:

    users:
      jenkins_admin:
        name: admin
        ssh_key_filename: jcasc
        password: "{{ lookup('password', 'credentials/jenkins_admin.txt chars=ascii_lowercase,digits length=16') }}"

  tasks:

  - name: Build custom fedora image
    containers.podman.podman_image:
      name: jenkins
      path: .
      force: yes
      build:
        format: docker

  - name: Start custom fedora container
    containers.podman.podman_container:
      name: jenkins
      image: jenkins
      recreate: yes
      ports:
        - "2222:22"
      env:
        AWS_ACCESS_KEY: local
        AWS_SECRET_ACCESS_KEY: local
        JENKINS_ADMIN_ID: "{{ users.jenkins_admin.name }}"
        JENKINS_ADMIN_PASSWORD: "{{ users.jenkins_admin.password }}"
