#!groovy

pipeline {
    agent any

    parameters {
        booleanParam(
            name: 'Destroy',
            defaultValue: false,
            description: 'Destroy existing build'
        )
    }

    environment {
        ENV = "dev"
        PROJECT_ID = "AB-utopia"
    }

    stages {
        stage("Create Stack") {
            when {
                expression {
                    !params.Destroy
                }
            }

            steps {
                dir("cloudformation") {
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: "jenkins",
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        script {
                            def hosted_zone_id = sh(
                              script: "aws route53 list-hosted-zones | jq '.HostedZones[0].Id' | sed 's/\\/hostedzone\\///'",
                              returnStdout: true
                            ).trim()
                            withCredentials([
                                string(
                                    credentialsId: "${ENV.toLowerCase()}/$PROJECT_ID/default",
                                    variable: 'SECRETS'
                                )
                            ]) {
                                def aws_secrets = readJSON text: SECRETS
                                sh """cat > parameters.json << EOF
[
  {"ParameterKey":"ProjectId",     "ParameterValue":"$PROJECT_ID"},
  {"ParameterKey":"HostedZoneID",  "ParameterValue":$hosted_zone_id},
  {"ParameterKey":"DBUserUsername","ParameterValue":"${aws_secrets.db_username}"},
  {"ParameterKey":"DBUserPassword","ParameterValue":"${aws_secrets.db_password}"},
  {"ParameterKey":"DBRootUsername","ParameterValue":"${aws_secrets.db_root_username}"},
  {"ParameterKey":"DBRootPassword","ParameterValue":"${aws_secrets.db_root_password}"}
]
EOF
                                """
                            }
                            sh "aws cloudformation create-stack --stack-name $PROJECT_ID --template-body file://template.yaml --parameters file://parameters.json --capabilities CAPABILITY_NAMED_IAM"
                            sh "aws cloudformation wait stack-create-complete --stack-name $PROJECT_ID"
                            sh "aws cloudformation describe-stacks --query 'Stacks[?StackName=='$PROJECT_ID'][].Outputs' --output json > output.json"
                            sh "aws s3 cp output.json s3://$s3_bucket/env:/$ENV/"
                        }
                    }
                }
            }
        }

        stage("Destroy Stack") {
            when {
                expression {
                    params.Destroy
                }
            }

            steps {
                dir("cloudformation") {
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: "jenkins",
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        sh "aws cloudformation delete-stack --stack-name $PROJECT_ID"
                        sh "aws cloudformation wait stack-delete-complete --stack-name $PROJECT_ID"
                    }
                }
            }
        }
    }
}
