#!groovy

pipeline {
    agent any

    parameters {
        booleanParam(
            name: 'Destroy',
            defaultValue: false,
            description: 'Destroy existing build'
        )
    }

    environment {
        ENV = "dev"
        PROJECT_ID = "AB-utopia"
        STACK_NAME = "AB"

        S3_BUCKET = PROJECT_ID.toLowerCase()
    }

    stages {
        stage("Create Stack") {
            when {
                expression {
                    !params.Destroy
                }
            }

            steps {
                dir("cloudformation") {
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: "jenkins",
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        script {
                            def hosted_zone_id = sh(
                              script: "aws route53 list-hosted-zones | jq '.HostedZones[0].Id' | sed 's/\\/hostedzone\\///'",
                              returnStdout: true
                            ).trim()
                            withCredentials([
                                string(
                                    credentialsId: "${ENV.toLowerCase()}/$PROJECT_ID/default",
                                    variable: 'SECRETS'
                                )
                            ]) {
                                def aws_secrets = readJSON text: SECRETS
                                sh """cat > parameters.json << EOF
[
  {"ParameterKey":"ProjectId",     "ParameterValue":"$PROJECT_ID"},
  {"ParameterKey":"HostedZoneID",  "ParameterValue":$hosted_zone_id},
  {"ParameterKey":"DBUserUsername","ParameterValue":"${aws_secrets.db_username}"},
  {"ParameterKey":"DBUserPassword","ParameterValue":"${aws_secrets.db_password}"},
  {"ParameterKey":"DBRootUsername","ParameterValue":"${aws_secrets.db_root_username}"},
  {"ParameterKey":"DBRootPassword","ParameterValue":"${aws_secrets.db_root_password}"}
]
EOF
                                """
                            }
                            //sh "aws cloudformation create-stack --stack-name $STACK_NAME --template-body file://template.yaml --parameters file://parameters.json --capabilities CAPABILITY_NAMED_IAM"
                            //sh "aws cloudformation wait stack-create-complete --stack-name $STACK_NAME"
                            def output_values = readJSON text: sh(
                                script: "aws cloudformation describe-stacks --query 'Stacks[?StackName==`$STACK_NAME`].Outputs[0]' --output json",
                                returnStdout: true
                            )
                            def result = [
                                public_subnets: [],
                                private_subnets: []
                            ]
                            for(output in output_values) {
                                if(output.OutputKey == "RDSEndpoint") {
                                    result.db_url = output.OutputValue
                                } else if(output.OutputKey == "VPCId") {
                                    result.vpc_id = output.OutputValue
                                } else if(output.OutputKey.startsWith("PublicSubnetId")) {
                                    result.public_subnets += output.OutputValue
                                } else if(output.OutputKey.startsWith("NATPrivateSubnetId")) {
                                    result.private_subnets += output.OutputValue
                                }
                            }
                            writeJSON file: 'output.json', json: result
                            sh "aws s3 cp output.json s3://$S3_BUCKET/env:/$ENV/"
                        }
                    }
                }
            }
        }

        stage("Destroy Stack") {
            when {
                expression {
                    params.Destroy
                }
            }

            steps {
                dir("cloudformation") {
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: "jenkins",
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        sh "aws cloudformation delete-stack --stack-name $STACK_NAME"
                        sh "aws cloudformation wait stack-delete-complete --stack-name $STACK_NAME"
                    }
                }
            }
        }
    }
}
