apiVersion: apps/v1
kind: Deployment
metadata:
  name: flights-deployment
  namespace: microservices
  labels:
    app: flights-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flights-microservice
  template:
    metadata:
      labels:
        app: flights-microservice
    spec:
      containers:
      - name: flights-microservice
        image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$PROJECT_ID-flights-microservice:latest
        imagePullPolicy: Always
        env:
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                key: db-url
                name: db-info
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                key: db-user
                name: db-info
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db-password
                name: db-info
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                key: jwt-secret
                name: jwt-secret
        ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: flights-service
  namespace: microservices
  labels:
    app: flights-microservice
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  selector:
    app: flights-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
