---
- hosts: 127.0.0.1
  connection: local

  vars:
    secrets: "{{ lookup('amazon.aws.aws_secret', '{{ env | lower }}/{{ project_id }}/default') }}"

  tasks:

  - name: Store CA auth in file
    shell: printf "{{ kubeconfig_certificate_authority_data }}">ca_auth
  - name: Connect to EKS cluster
    shell:
      kubectl config
        --kubeconfig="{{ project_id }}"
        set-cluster "{{ project_id }}"
        --server="{{ eks_endpoint }}"
        --certificate-authority=ca_auth
    register: kubeconfig

  - debug: msg="{{ kubeconfig.stdout }}"

  - name: Apply API service
    shell:
      kubectl apply -f ../../kubernetes/api-service.yml
  - name: Apply API deployment
    shell:
      envsubst < ../../kubernetes/api-deployment.yml | kubectl apply -f -
    environment:
      DB_USERNAME: "{{ secrets.db_username }}"
      DB_PASSWORD: "{{ secrets.db_password }}"
      JWT_SECRET: "{{ secrets.jwt_secret }}"

