---
- hosts: 127.0.0.1
  connection: local

  vars:
    secrets: "{{ lookup('amazon.aws.aws_secret', '{{ env | lower }}/{{ project_id }}/default') }}"

  tasks:

  - name: Store CA auth in file
    shell: printf "{{ kubeconfig_certificate_authority_data }}">ca_auth
  - name: Connect to EKS cluster
    shell:
      aws eks --region "{{ region }}" update-kubeconfig --name "{{ project_id }}"
      kubectl config \
        --kubeconfig="{{ project_id }}" \
        set-cluster "{{ project_id }}"  \
        --server="{{ eks_endpoint }}" \
        --certificate-authority=ca_auth

  - name: Apply kubectl configs
    shell:
      kubectl apply -f ../../kubernetes/api-service.yml
      envsubst < ../../kubernetes/api-deployment.yml | kubectl apply -f -

  #- debug: msg="{{ caller_facts }}"
