---
- hosts: 127.0.0.1
  connection: local

  vars:
    env: "{{ lookup('env', 'ENV') }}"
    project_id: "{{ lookup('env', 'PROJECT_ID') }}"
    secrets: "{{ lookup('amazon.aws.aws_secret', '{{ env | lower }}/{{ project_id }}/default') }}"

  tasks:

  - name: Create Fargate Profile
    community.aws.aws_eks_cluster:
      name: "{{ project_id }}"
      version: 1.14
      role_arn: "{{ eks_role_arn }}"
      subnets: ["{{ private_subnet_ids }}"]
    register: caller_facts

  - debug: msg="{{ caller_facts }}"

  - name: Create an EKS cluster
    community.aws.aws_eks_cluster:
      name: "{{ project_id }}"
      version: 1.14
      role_arn: "{{ eks_role_arn }}"
      subnets: ["{{ private_subnet_ids }}"]
    register: caller_facts

  - debug: msg="{{ caller_facts }}"
