---
- hosts: 127.0.0.1
  connection: local

  vars:
    env: "{{ lookup('env', 'ENV') }}"
    project_id: "{{ lookup('env', 'PROJECT_ID') }}"
    secrets: "{{ lookup('amazon.aws.aws_secret', '{{ env | lower }}/{{ project_id }}/default') }}"

  tasks:

  - debug: msg="{{ caller_facts }}"
