version: '3'
x-aws-vpc: 'vpc-0f3dce67ace642302'

services:
  flights-microservice:
    image: ${FLIGHTS_REGISTRY_URI}:${FLIGHTS_TAG}
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

  users-microservice:
    image: ${USERS_REGISTRY_URI}:${USERS_TAG}
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

  bookings-microservice:
    image: ${BOOKINGS_REGISTRY_URI}:${BOOKINGS_TAG}
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

