version: '3'

networks:
  api-net:
  nginx-net:

services:
  nginx:
    image: nginx:1.16.0-alpine
    depends_on:
       - flights-microservice
       - users-microservice
       - bookings-microservice
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - api-net
      - nginx-net
    ports:
      - 80:80

  data-producer:
    image: austinbaugh/utopia-data-producer:0.0.3-SNAPSHOT
    depends_on:
       - nginx
    environment:
      UTOPIA_API_URL: http://nginx:80
    networks:
      - nginx-net
    ports:
      - 5000:5000

  flights-microservice:
    image: austinbaugh/utopia-flights-microservice:0.0.3-SNAPSHOT
    env_file: ../.env
    networks:
      - api-net
    expose:
      - 8080

  users-microservice:
    image: austinbaugh/utopia-users-microservice:0.0.3-SNAPSHOT
    env_file: ../.env
    networks:
      - api-net
    expose:
      - 8080

  bookings-microservice:
    image: austinbaugh/utopia-bookings-microservice:0.0.3-SNAPSHOT
    env_file: ../.env
    networks:
      - api-net
    expose:
      - 8080

