#!groovy
pipeline {
    agent any

    stages {
        stage('Up for 2min') {
            steps {
                sh "echo DB_URL=${env.DB_URL} > .env"
                sh "echo DB_USERNAME=${env.DB_USERNAME} >> .env"
                sh "echo DB_PASSWORD=${env.DB_PASSWORD} >> .env"
                sh "echo JWT_SECRET=${env.JWT_SECRET} >> .env"
                sh "docker-compose -f docker-compose/docker-compose.yml up -d"
                sh "sleep 120"
            }
        }

        stage('Down') {
            steps {
                sh "docker-compose -f docker-compose/docker-compose.yml down"
                sh "rm .env"
            }
        }
    }
}
