#!groovy
pipeline {
    agent any

    stages {
        stage('Up for 30sec') {
            steps {
                sh "docker-compose up -d"
                sh "sleep 30"
            }
        }

        stage('Down') {
            steps {
                sh "docker-compose down"
            }
        }
    }
}
