---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ${CLUSTER_NAME}
  region: ${AWS_REGION}
iam:
  withOIDC: true
fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
