#!groovy
pipeline {
    agent any

    parameters {
        booleanParam(
            name: 'Destroy',
            defaultValue: false,
            description: 'Destroy existing build'
        )
    }

    environment {
        PROJECT_ID = "AB-utopia"
        ENV = "dev"

        DOMAIN_ZONE = "hitwc.link"
        DOMAIN_RECORD = "${PROJECT_ID.toLowerCase()}.hitwc.link"
        S3_BUCKET = PROJECT_ID.toLowerCase()
    }

    stages {
        stage('Create cluster') {
            when {
                expression {
                    !params.Destroy
                }
            }
            steps {
                dir("eks") {
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: "jenkins",
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        script {
                            // get tf output
                            sh "aws s3 cp s3://$S3_BUCKET/env:/$ENV/output.json ."
                            def tf_output = readJSON file: 'output.json'
                            env.VPC_ID = tf_output.vpc_id
                            env.DB_URL = tf_output.db_url
                            env.ACM_CERT_ARN = tf_output.acm_cert_arn
                            env.R53_ZONE_ID = tf_output.r53_zone_id
                            // create eks cluster
                            def aws_account_id = sh(
                                script: 'aws sts get-caller-identity --query "Account" --output text',
                                returnStdout: true
                            ).trim()
                            def region = sh(
                                script: 'aws configure get region',
                                returnStdout: true
                            ).trim()
                            def public_subnets = tf_output.subnet_ids.public.toList().join(',')
                            def private_subnets = tf_output.subnet_ids.nat_private.toList().join(',')
                            sh """
                                eksctl create cluster \
                                    --name $PROJECT_ID \
                                    --region $region \
                                    --nodes 2 \
                                    --node-type t3.small \
                                    --alb-ingress-access \
                                    --vpc-public-subnets $public_subnets \
                                    --vpc-private-subnets $private_subnets
                            """
                        }
                    }
                }
            }
        }

        stage('Setup AWS load balancer ingress controller') {
            when {
                expression {
                    !params.Destroy
                }
            }
            steps {
                dir("eks") {
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: "jenkins",
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        script {
                            def aws_account_id = sh(
                                script: 'aws sts get-caller-identity --query "Account" --output text',
                                returnStdout: true
                            ).trim()
                            def region = sh(
                                script: 'aws configure get region',
                                returnStdout: true
                            ).trim()
                            // Associate IAM OIDC provider for ALB
                            sh """
                                eksctl utils associate-iam-oidc-provider \
                                    --region "$region" \
                                    --cluster "$PROJECT_ID" \
                                    --approve
                            """

                            // Create IAM service account w/ role & attached policies for ALB
                            sh """
                                eksctl create iamserviceaccount \
                                    --name=aws-load-balancer-controller \
                                    --cluster "$PROJECT_ID" \
                                    --namespace=kube-system \
                                    --attach-policy-arn="arn:aws:iam::$aws_account_id:policy/AWSLoadBalancerControllerIAMPolicy" \
                                    --attach-policy-arn="arn:aws:iam::$aws_account_id:policy/AWSLoadBalancerControllerAdditionalIAMPolicy" \
                                    --override-existing-serviceaccounts \
                                    --approve
                            """

                            // Install the TargetGroupBinding custom resource definitions
                            sh "kubectl apply -k 'github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master'"

                            // Install AWS load balancer controller
                            sh """
                                helm upgrade \
                                    -i aws-load-balancer-controller aws-load-balancer-controller \
                                    --repo https://aws.github.io/eks-charts \
                                    --set clusterName="$PROJECT_ID" \
                                    --set vpcId="$VPC_ID" \
                                    --set region="$region" \
                                    --set serviceAccount.create=false \
                                    --set serviceAccount.name=aws-load-balancer-controller \
                                    -n kube-system
                            """
                        }
                    }
                }
            }
        }

        stage('Deploy microservices') {
            when {
                expression {
                    !params.Destroy
                }
            }
            steps {
                dir("eks") {
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: "jenkins",
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        script {
                            def aws_account_id = sh(
                                script: 'aws sts get-caller-identity --query "Account" --output text',
                                returnStdout: true
                            ).trim()
                            def region = sh(
                                script: 'aws configure get region',
                                returnStdout: true
                            ).trim()
                            // Make sure microservices namespace is present
                            sh "kubectl apply -f k8s/namespace.yml"
                            // Set k8s secrets from stdin literals
                            withCredentials([
                                string(
                                    credentialsId: "${ENV.toLowerCase()}/$PROJECT_ID/default",
                                    variable: 'SECRETS'
                                )
                            ]) {
                                def aws_secrets = readJSON text: SECRETS
                                sh """
                                    kubectl create secret generic db-info \
                                        -n microservices \
                                        --from-literal db-url="mysql://$DB_URL:3306/utopia" \
                                        --from-literal db-user="${aws_secrets.db_username}" \
                                        --from-literal db-password="${aws_secrets.db_password}"
                                    kubectl create secret generic jwt-secret \
                                        -n microservices \
                                        --from-literal jwt-secret="${aws_secrets.jwt_secret}"
                                """
                            }

                            // Deploy microservices
                            for(microservice in [
                                "flights-microservice",
                                "bookings-microservice",
                                "users-microservice"
                            ]) {
                                sh """
                                    PROJECT_ID="${PROJECT_ID.toLowerCase()}" \
                                    AWS_ACCOUNT_ID="$aws_account_id" \
                                    AWS_REGION="$region" \
                                        envsubst < "k8s/${microservice}.yml" | kubectl apply -f -
                                """
                            }
                            // Apply ingress rules
                            sh """
                                DOMAIN="$DOMAIN_RECORD" \
                                AWS_REGION="$region" \
                                AWS_ACCOUNT_ID="$aws_account_id" \
                                ACM_CERT_ARN="$ACM_CERT_ARN" \
                                    envsubst < k8s/ingress.yml | kubectl apply -f -
                            """
                        }
                    }
                }
            }
        }

        stage('Update R53 record w/ external-dns') {
            when {
                expression {
                    !params.Destroy
                }
            }
            steps {
                dir("eks") {
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: "jenkins",
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        script {
                            def aws_account_id = sh(
                                script: 'aws sts get-caller-identity --query "Account" --output text',
                                returnStdout: true
                            ).trim()
                            def region = sh(
                                script: 'aws configure get region',
                                returnStdout: true
                            ).trim()
                            // Create IAM service account w/ role & attached policies for external-dns
                            sh """
                                eksctl create iamserviceaccount \
                                    --name=external-dns \
                                    --cluster "$PROJECT_ID" \
                                    --namespace=default \
                                    --attach-policy-arn=arn:aws:iam::$aws_account_id:policy/AllowExternalDNSUpdates \
                                    --override-existing-serviceaccounts \
                                    --approve
                            """

                            // Apply external-dns deployment manifest
                            sh """
                                DOMAIN="$DOMAIN_ZONE" \
                                AWS_ACCOUNT_ID="$aws_account_id" \
                                R53_ZONE_ID="$R53_ZONE_ID" \
                                IAM_SERVICE_ROLE_NAME="$PROJECT_ID-external-dns" \
                                    envsubst < k8s/external-dns.yml | kubectl apply -f -
                            """
                        }
                    }
                }
            }
        }

        stage('Destroy EKS') {
            when {
                expression {
                    params.Destroy
                }
            }
            steps {
                dir("eks") {
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: "jenkins",
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        script {
                            // Get tf output
                            sh "aws s3 cp s3://$S3_BUCKET/env:/$ENV/output.json ."
                            // tear-down eks cluster
                            def region = sh(
                                script: 'aws configure get region',
                                returnStdout: true
                            ).trim()
                            sh "eksctl delete cluster --name $PROJECT_ID --region $region"
                        }
                    }
                }
            }
        }
    }
}

