#!groovy
pipeline {
    agent any

    parameters {
        booleanParam(
            name: 'Destroy',
            defaultValue: false,
            description: 'Destroy existing build'
        )
    }

    environment {
        PROJECT_ID = "AB-utopia"
        ENV = "dev"
        S3_BUCKET = PROJECT_ID.toLowerCase()
    }

    stages {
        stage('Deploy EKS') {
            when {
                expression {
                    !params.Destroy
                }
            }
            steps {
                dir("eks") {
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: "jenkins",
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        sh "aws s3 cp s3://$S3_BUCKET/env:/$ENV/output.json ."
                        def py3_path = sh(script: 'which python3', returnStdout:true)
                        sh '''
                            python3 -m venv tmp/
                            . tmp/bin/activate
                            pip3 install ansible
                            ansible-playbook playbooks/up.yaml -e @output.json
                            . $py3_path
                        '''
                    }
                }
            }
        }

        stage('Destroy EKS') {
            when {
                expression {
                    params.Destroy
                }
            }
            steps {
                dir("eks") {
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: "jenkins",
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        sh """
                            ansible-playbook playbooks/down.yaml \
                                -e @output.json \
                                -e "env=$ENV project_id=$PROJECT_ID"
                        """
                    }
                }
            }
        }
    }
}

