#!groovy
pipeline {
    agent any

    parameters {
        string(
            name: 'ProjectId',
            defaultValue: 'AB-utopia',
            description: 'Identifier applied to all names'
        )
        choice(
            name: 'Env',
            choices: ['Dev', 'Staging', 'Prod'],
            description: 'Deployment environment'
        )
        choice(
            name: 'Operation',
            choices: ['Up', 'Down'],
            description: 'Bring up or take down ECS cluster'
        )
    }

   environment {
        COMMIT_HASH = sh(
            returnStdout: true,
            script: "git rev-parse --short=8 HEAD"
        ).trim()
        S3_BUCKET = params.ProjectId.toLowerCase()
        REGION = sh(
            script: 'aws configure get region',
            returnStdout: true
        ).trim()
        AWS_ACCOUNT_ID = sh(
            script: '''
                aws sts get-caller-identity \
                    --query "Account" \
                    --output text
            ''',
            returnStdout: true
        ).trim()

        ecr_uri = "${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"
   }

    stages {
        stage('Configure Environment Inputs') {
            steps {
                script {
                    sh "aws s3 cp s3://$S3_BUCKET/env:/${params.Env}/output.txt ."
                    def tf_output = readProperties file: 'output.txt'
                    env.DOMAIN = tf_output.domain
                    env.VPC_ID = tf_output.vpc_id
                    env.DB_URL = "mysql://${tf_output.db_url}/utopia"
                    env.ALB_ID = tf_output.alb_id

                    def image_prefix = "$ecr_uri/${params.Env.toLowerCase()}"
                    env.REVERSE_PROXY_IMAGE   = "$image_prefix-reverse-proxy:latest"
                    env.USERS_MICROSERVICE_IMAGE    = "$image_prefix-users-microservice:latest"
                    env.BOOKINGS_MICROSERVICE_IMAGE = "$image_prefix-bookings-microservice:latest"
                    env.FLIGHTS_MICROSERVICE_IMAGE  = "$image_prefix-flights-microservice:latest"
                }
            }
        }

        stage('Deploy ECS') {
            when {
                expression {
                    params.Operation == "Up"
                }
            }
            steps {
                sh "ln -s ecs ${params.ProjectId}-ecs"
                dir("${params.ProjectId}-ecs") {
                    sh "ansible-playbook ../ansible/ecs-up.yaml -f 10"
                }
            }
        }

        stage('Destroy ECS') {
            when {
                expression {
                    params.Operation == "Down"
                }
            }
            steps {
                dir("${params.ProjectId}-ecs") {
                    sh "ansible-playbook ../ansible/ecs-down.yaml -f 10"
                }
                sh "rm -f ${params.ProjectId}-ecs"
            }
        }
    }
}
