---
- hosts: 127.0.0.1
  connection: local

  vars:
    env: "{{ lookup('env', 'ENV') }}"
    project_id: "{{ lookup('env', 'PROJECT_ID') }}"
    secrets: "{{ lookup('amazon.aws.aws_secret', '{{ env | lower }}/{{ project_id }}/default') }}"

  tasks:

  - name: use pre-created ecs docker context
    shell: docker context use "{{ project_id }}-ecs"

  - name: set secrets as environment variables
    shell:
      export DB_USERNAME="{{ secrets.db_username }}"
      export DB_PASSWORD="{{ secrets.db_password }}"
      export JWT_TOKEN="{{ secrets.jwt_token }}"

  - name: stand up ecs cluster
    shell: docker compose up
    register: ecs_up
    tags: ecs_up

  - debug: msg="{{ ecs_up.stderr }}"

  - debug: msg="{{ ecs_up.stdout }}"
