---
- hosts: 127.0.0.1
  connection: local

  vars:
    env: "{{ lookup('env', 'ENV') }}"
    project_id: "{{ lookup('env', 'PROJECT_ID') }}"
    secrets: "{{ lookup('amazon.aws.aws_secret', '{{ env | lower }}/{{ project_id }}/default') }}"

  tasks:

  - name: use pre-created ecs docker context
    shell: docker context use "{{ project_id }}-ecs"

  - name: stand up ecs cluster
    shell: docker compose up
    environment:
      VPC_ID: "{{ lookup('env', 'VPC_ID') }}"
      ALB_ID: "{{ lookup('env', 'ALB_ID') }}"
      DB_URL: "{{ lookup('env', 'DB_URL') }}"
      DB_USERNAME: "{{ secrets.db_username }}"
      DB_PASSWORD: "{{ secrets.db_password }}"
      JWT_SECRET: "{{ secrets.jwt_secret }}"
      REVERSE_PROXY_IMAGE: "{{ lookup('env', 'REVERSE_PROXY_IMAGE') }}"
      FLIGHTS_IMAGE: "{{ lookup('env', 'FLIGHTS_IMAGE') }}"
      BOOKINGS_IMAGE: "{{ lookup('env', 'BOOKINGS_IMAGE') }}"
      USERS_IMAGE: "{{ lookup('env', 'USERS_IMAGE') }}"
    register: ecs_up
    tags: ecs_up

  - debug: msg="{{ ecs_up.stderr }}"

  - debug: msg="{{ ecs_up.stdout }}"
