---
- hosts: managed_node

  tasks:
    - name: copy amazon-linux.pkr.hcl
      copy:
        src: amazon-linux.pkr.hcl
        dest: .
    - name: packer init
      shell: packer init .
    - name: packer fmt
      shell: packer fmt .
    - name: packer validate
      shell: packer validate .
    - name: packer build
      shell: packer build amazon-linux.pkr.hcl
