apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookings-microservice
  namespace: microservices
  labels:
    app: bookings-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookings-microservice
  template:
    metadata:
      labels:
        app: bookings-microservice
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: bookings-microservice
        image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$PROJECT_ID-bookings-microservice:latest
        imagePullPolicy: Always
        env:
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                key: db-url
                name: db-info
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                key: db-user
                name: db-info
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db-password
                name: db-info
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                key: jwt-secret
                name: jwt-secret
        ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: bookings-microservice
  namespace: microservices
  labels:
    app: bookings-microservice
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  selector:
    app: bookings-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
