apiVersion: v1
kind: Namespace
metadata:
  name: aws-observability
  labels:
    aws-observability: enabled
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  output.conf: |
    [OUTPUT]
        Name  es
        Match *
        Host $ELK_HOST
        Logstash_Format On
        Logstash_Prefix_Key $LOGS_PREFIX
        Path                  /elasticsearch
        Logstash_Format       On
        Replace_Dots          On
        Retry_Limit           False
        tls On
        Port 443
        HTTP_User $ELK_USERNAME
        HTTP_Passwd $ELK_PASSWORD

  parsers.conf: |
    [PARSER]
        Name crio
        Format Regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>P|F) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

  filters.conf: |
     [FILTER]
        Name parser
        Match *
        Key_name log
        Parser crio
