---
- hosts: 127.0.0.1
  connection: local
  vars:

    project_id: AB-utopia
    region: us-west-2

  tasks:

  - community.aws.aws_kms:
      alias: "{{ project_id }}-tf-state-s3-encryption"
      state: present
      region: "{{ region }}"
      tags:
        Name: "{{ project_id }}-tf-state-s3-encryption"
        Purpose: encrypt_s3_bucket
    register: kms

  - amazon.aws.s3_bucket:
      name: "{{ project_id | lower }}-tf-state-sync"
      state: present
      region: "{{ region }}"
      encryption: "aws:kms"
      encryption_key_id: "{{ kms.key_id }}"

  - community.aws.dynamodb_table:
      name: "{{ project_id | lower }}"
      state: present
      region: "{{ region }}"
      hash_key_name: LockID
      hash_key_type: STRING
      read_capacity: 20
      write_capacity: 20
      tags:
        Name: "{{ project_id }}-tf-state-locking"
