---
- hosts: 127.0.0.1
  connection: local

  vars:
    ## Get tf output from S3
    project_id: AB-utopia
    vpc_id: vpc-09ba651230e7b79fe
    environment: Dev
    db_security_group_id: sg-04119c0be0c817ec9
    private_subnet_ids:
      - subnet-0dcbbfb382383795a
      - subnet-0113a077f761515c4
    public_subnet_ids:
      - subnet-03172ec61f12bdd6e
      - subnet-09b4ecefc7812eb31
    eks_sec_group:
    ## Obtain db user creds from secrets manager
    secrets: lookup( \
      'amazon.aws.aws_secret', \
      '{{ environment | lower }}/{{ project_id }}/default' \
    )
    username: "{{ secrets.user_username }}"
    password: "{{ secrets.user_password }}"
    jwt_token: "{{ secrets.jwt_token }}"

  tasks:

  - name: Get
    amazon.aws.aws_s3:
      bucket: ab-utopia
      object: "s3://env:/{{ environment }}/output.txt"
      dest: .
      mode: get

  # Create EKS cluster and attach to ALB

  - name: Create an EKS cluster
    community.aws.aws_eks_cluster:
      name: "{{ project_id }}"
      version: 1.14
      role_arn: "{{ eks_role_arn }}"
      subnets: ["{{ private_subnet_ids }}"]
    register: caller_facts

  ## Create Bastion as EC2 instance w/ AMI, SecGroup, & S3 read permissions from IAM
  ## Wait for RDS to become available
  - name: Create bastion host
    amazon.aws.ec2_instance:
      name: "{{ project_id }}-bastion-host"
      key_name: "prod-ssh-key"
      vpc_subnet_id: "{{ public_subnet_ids | shuffle }} "
      instance_type: t2.micro
      security_group:
      network:
        assign_public_ip: true
      image_id:
      tags:
        Name: "{{ project_id }}-bastion-host"
