---
- hosts: 127.0.0.1
  connection: local

  vars:
    ## Get output.tf from S3
    project_id: AB-utopia
    vpc_id: vpc-09ba651230e7b79fe
    db_subnet_group_name:
    db_security_group_id:
    private_subnet_ids:
      - subnet-0dcbbfb382383795a
      - subnet-0113a077f761515c4
    #public_subnet_ids:
    #  -
    #  -
    ## Obtain db root & user creds from secrets manager
    root_username: root
    root_password: temporary
    user_username: user
    user_password: temporary

  tasks:

  ## Create RDS w/ admin creds
  - name: Create RDS instance
    community.aws.rds_instance:
      id: "{{ project_id | lower }}"
      allocated_storage: 10
      engine: mysql
      engine_version: 8.0
      db_instance_class: db.t2.micro
      username: "{{ root_username }}"
      password: "{{ root_password }}"
      skip_final_snapshot: True
      db_subnet_group_name: "{{ db_subnet_group_name }}"
      vpc_security_group_ids: "{{ db_security_group_id }}"

  ## Wait for RDS to become available
  ## Create Bastion as EC2 instance w/ AMI, SecGroup, & S3 read permissions from IAM
  ## Have user_data create DB schema & DB user using root creds and poweroff EC2 instance
