---
- hosts: 127.0.0.1
  connection: local

  vars:
    project_id: "{{ lookup('env', 'PROJECT_ID') }}"
    domain_zone: "hitwc.link"
    domain_record: "{{ project_id | lower }}.hitwc.link"

  tasks:

  - name: Get AWS account id
    shell:
      aws sts get-caller-identity
        --query "Account"
        --output text
    register: aws_account_id
  - name: Get AWS region
    shell: aws configure get region
    register: aws_region

  - name: Connect to EKS cluster
    shell: aws eks --region "{{ aws_region.stdout }}" update-kubeconfig --name "{{ project_id }}"

  - name: Remove Route53 record
    community.aws.route53:
      zone: "{{ domain_zone }}"
      record: "{{ domain_record }}"
      type: CNAME
      state: absent

  - name: Delete microservices
    shell: kubectl delete all --all -n microservices

  - name: Delete cert-manager
    shell: kubectl delete all --all -n cert-manager

  - name: Delete ingress-nginx namespace
    shell: kubectl delete all --all -n ingress-nginx
