version: '3'

networks:
  api-net:

services:
  api-gateway:
    image: ${API_GATEWAY_REGISTRY_URI}:${API_GATEWAY_TAG}
    depends_on:
      - flights-microservice
      - users-microservice
      - bookings-microservice
    environment:
      DOMAIN: 127.0.0.1
      FLIGHTS: flights-microservice
      BOOKINGS: bookings-microservice
      USERS: users-microservice
    networks:
      - api-net
    ports:
      - 80:80

  flights-microservice:
    image: ${FLIGHTS_REGISTRY_URI}:${FLIGHTS_TAG}
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - api-net
    expose:
      - 8080

  users-microservice:
    image: ${USERS_REGISTRY_URI}:${USERS_TAG}
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - api-net
    expose:
      - 8080

  bookings-microservice:
    image: ${BOOKINGS_REGISTRY_URI}:${BOOKINGS_TAG}
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - api-net
    expose:
      - 8080

